#!/usr/bin/env bash

DATE=`date +%Y%m%d-%H:%M:%S-%N`

rm /tmp/main.*.log
#rm /Users/piotr/Desktop/Code/DeSo/logs/n0/*


(cd ../../ && go build -o backend -gcflags="all=-N -l" main.go && \
  ./backend run \
  --glog-v=0 \
  --glog-vmodule="*bitcoin_manager*=0,*balance*=0,*view*=0,*frontend*=0,*peer*=0,*addr*=0,*network*=0,*utils*=0,*connection*=0,*main*=0,*server*=0,*mempool*=0,*miner*=0,*blockchain*=0" \
  --num-mining-threads=1  \
  --admin-public-keys=* \
  --protocol-port=17000 \
  --api-port=17001 \
  --super-admin-public-keys=* \
  --miner-public-keys=BC1YLgKZyfgyNntCMXAZYExM8JooYqrYvVsrR8d8XVxorDruYFdq31p \
  --starter-deso-seed='road congress client market couple bid risk escape artwork rookie artwork food' \
  --data-dir=$HOME/data_dirs/n98_1  \
  --block-cypher-api-key=092dae962ea44b02809a4c74408b42a1 \
  --min-satoshis-for-profile=0 \
  --hypersync=true \
  --disable-slow-sync=false \
  --connect-ips=deso-seed-2.io:17000 \
  --run-hot-feed-routine=true \
  --log-dir=/Users/piotr/Desktop/Code/DeSo/logs/n0 \
  --txindex=true \
)

# --max-sync-block-height=10977 \
# --txindex=true \
# These are nodes that can be relied upon if the decentralized seed
# node discovery mechanism fails.
# --connectips=35.232.92.5:17000
