#!/usr/bin/env bash

DATE=`date +%Y%m%d-%H:%M:%S-%N`

# Seeds. This is the account corresponding to the public key below.
# * Mnemonic:
#   * verb find card ship another until version devote guilt strong lemon six
# * DeSo public keys:
#   * BC1YLg7Bk5sq9iNY17bAwoAYiChLYpmWEi6nY6q5gnA1UQV6xixHjfV
#   * tBCKVERmG9nZpHTk2AVPqknWc1Mw9HHAnqrTpW1RnXpXMQ4PsQgnmV
# * Bitcoin burn addresses:
#   * mhziDsPWSMwUqvZkVdKY92CjesziGP3wHL
#   * 13UkvpJXdLWE4p68n4MAK6zQntQ1RHixyM

rm /tmp/main.*.log

# "-gcflags=”all=-N -l" was added to get GoLand debugger (Delve) to work, see
# https://blog.jetbrains.com/go/2019/02/06/debugging-with-goland-getting-started/
#
# "If you are running with Go 1.10 or newer, you need to add ` -gcflags=”all=-N -l” `
# to the ` go build ` command."

(cd ../../ && go build -o backend -gcflags="all=-N -l" -tags="relic" main.go && ./backend run \
  --glog-v=0 \
  --glog-vmodule="*api*=0,*bitcoin_manager*=2,*balance*=0,*frontend*=0,*peer*=0,*addr*=0,*network*=0,*utils*=0,*connection*=0,*main*=0,server*=0,*mempool*=0,*miner*=0,*blockchain*=0,*block_producer*=1" \
  --add-ips=localhost:19000 \
  --testnet=true  \
  --regtest \
  --api-port=18001 \
  --protocol-port=18000 \
  --txindex \
  --admin-public-keys=* \
  --super-admin-public-keys=* \
  --num-mining-threads=1 \
  --miner-public-keys=BC1YLg7Bk5sq9iNY17bAwoAYiChLYpmWEi6nY6q5gnA1UQV6xixHjfV \
  --block-producer-seed='verb find card ship another until version devote guilt strong lemon six' \
  --pos-validator-seed='verb find card ship another until version devote guilt strong lemon six' \
  --starter-deso-seed='road congress client market couple bid risk escape artwork rookie artwork food' \
  --data-dir=/tmp/n0_test_00000 \
  --access-control-allow-origins=http://localhost:4200,http://localhost:80,http://localhost:18002,http://localhost:4201,http://localhost:18001,http://localhost:3000,localhost:3000 \
  --secure-header-allow-hosts=localhost:4200 \
  --secure-header-development=true \
  --block-cypher-api-key=092dae962ea44b02809a4c74408b42a1 \
  --min-satoshis-for-profile=0 \
  --expose-global-state=true \
  --show-processing-spinners=true \
  --comp-profile-creation=true \
  --metamask-airdrop-deso-nanos-amount=1000 )
