#!/usr/bin/env bash

DATE=`date +%Y%m%d-%H:%M:%S-%N`

COMMAND="./backend run
  --glog-v=0
  --glog-vmodule="*bitcoin-manager*=0,*balance*=0,*frontend*=0,*peer*=2,*addr*=0,*network*=0,*utils*=0,*connection*=0,*main*=0,*server*=0,*mempool*=0,*miner*=0,*blockchain*=0,*block-view*=0"
  --connect-ips=localhost:18000
  --target-outbound-peers=1
  --testnet=true 
  --regtest
  --trusted-block-producer-public-keys=BC1YLiQ86kwXUy3nfK391xht7N72UmbFY6bGrUsds1A7QKZrs4jJsxo
  --trusted-block-producer-start-height=5
  --api-port=19001
  --protocol-port=19000
  --num-mining-threads=1
  --data-dir=/tmp/n1-0000000003
  --block-cypher-api-key=092dae962ea44b02809a4c74408b42a1"

rm /tmp/main.*.log
(cd ../../ && go build -o backend main.go && $COMMAND )

exit
