#!/usr/bin/env bash

DATE=`date +%Y%m%d-%H:%M:%S-%N`

COMMAND="./backend run
  --glog-v=0
  --glog-vmodule="*bitcoin-manager*=0,*balance*=0,*frontend*=0,*peer*=0,*addr*=0,*network*=0,*utils*=0,*connection*=0,*main*=0,*server*=0,*mempool*=0,*miner*=2,*blockchain*=0"
  --testnet=true
  --regtest
  --connect-ips=localhost:19000
  --api-port=20001
  --protocol-port=20000
  --private-mode=true
  --num-mining-threads=1
  --data-dir=/tmp/fe2-$DATE
  --block-cypher-api-key=092dae962ea44b02809a4c74408b42a1"

  # --miner_public_keys=

rm /tmp/main.*.log
(cd ../../ && go build -o backend main.go && $COMMAND )


