#!/usr/bin/env bash

DATE=`date +%Y%m%d-%H:%M:%S-%N`
#rm /Users/piotr/Desktop/Code/DeSo/logs/n1/*

(cd ../../ && go build -o backend -gcflags="all=-N -l" main.go && ./backend run \
  --glog-v=2 \
  --glog-vmodule="*bitcoin_manager*=2,*balance*=2,*view*=2,*frontend*=2,*peer*=2,*addr*=2,*network*=2,*utils*=0,*connection*=2,*main*=0,*server*=2,*mempool*=2,*miner*=2,*blockchain*=2" \
  --connect-ips="localhost:17000" \
  --api-port=18001 \
  --protocol-port=18000 \
  --admin-public-keys=* \
  --super-admin-public-keys=* \
  --max-sync-block-height=100 \
  --hyper-sync=true \
  --run-hot-feed-routine=true \
  --starter-deso-seed='road congress client market couple bid risk escape artwork rookie artwork food' \
  --block-cypher-api-key=092dae962ea44b02809a4c74408b42a1 \
  --data-dir=$HOME/data_dirs/n4_34 \
  --log-dir=/Users/piotr/Desktop/Code/DeSo/logs/n4/test31 \
)
